# Site settings
title: 零博客
description: Read blog on demand.
baseurl: "/blog" # the subpath of your site, e.g. /blog
url: "https://agora0.gitlab.io" # the hostname & protocol, e.g. http://example.com
github_username: agorahub

# Build settings
timezone: Asia/Singapore
future: true
theme: minima
exclude:
  - _posts/2024-04*
  - _posts/2024-03*
  - _posts/2024-02*
  - _posts/2024-01*
  - _posts/2023*
  - _posts/2022*
  - _posts/2021*
  - _posts/2020*
  - _posts/201*
paginate: 50
feed:
  posts_limit: 100
plugins:
  - jekyll-feed
  - jekyll-paginate

