# Site settings
title: 零博客
description: >- # this means to ignore newlines until "baseurl:"
  Read blog on demand.
baseurl: "/blog" # the subpath of your site, e.g. /blog
url: "https://agora0.gitlab.io" # the hostname & protocol, e.g. http://example.com
github_username: agorahub

# Build settings
timezone: Asia/Singapore
future: true
theme: minima
exclude:
  - _posts/2021-09*
  - _posts/2021-08*
  - _posts/2021-07*
  - _posts/2021-06*
  - _posts/2021-05*
  - _posts/2021-04*
  - _posts/2021-03*
  - _posts/2021-02*
  - _posts/2021-01*
  - _posts/2020*
  - _posts/201*
paginate: 50
feed:
  posts_limit: 100
plugins:
  - jekyll-feed
  - jekyll-paginate

